### ISSUE TITLE
Make feature specs compatible with Ruby 2.4 (upgrade webmock/VCR)

### ISSUE THREAD

**Issue by samphilipd** [piotrmurach/github#304]
Recording new feature specs fails on Ruby > 2.3 due to an incompatibility with the old version of webmock.

```
Feature: Projects API

  Background:                                               # features/repos/projects.feature:3
    Given I have "Github::Client::Repos::Projects" instance # features/step_definitions/github_api_steps.rb:8

  Scenario: List                                                      # features/repos/projects.feature:6
    Given I want to list resources with the following params:         # features/step_definitions/github_api_steps.rb:49
      | user       | repo   |
      | samphilipd | github |
    When I make request within a cassette named "repos/projects/list" # features/step_definitions/common_steps.rb:5
      undefined method `<<' for {:read_timeout=>60, :continue_timeout=>nil, :debug_output=>nil}:Hash
      Did you mean?  < (NoMethodError)
      ./lib/github_api/response/follow_redirects.rb:84:in `perform_with_redirection'
      ./lib/github_api/response/follow_redirects.rb:72:in `call'
      ./lib/github_api/request/basic_auth.rb:32:in `call'
      ./lib/github_api/request/oauth2.rb:24:in `call'
      ./lib/github_api/request/jsonize.rb:23:in `call'
      ./lib/github_api/request.rb:69:in `call'
      ./lib/github_api/request/verbs.rb:20:in `get_request'
      ./lib/github_api/client/repos/projects.rb:33:in `list'
      ./lib/github_api/api.rb:237:in `block in execute'
      ./lib/github_api/api.rb:224:in `run_callbacks'
      ./lib/github_api/api.rb:236:in `execute'
      ./lib/github_api/api.rb:196:in `block in method_added'
      ./features/step_definitions/github_api_steps.rb:72:in `/^I make request$/'
      ./features/step_definitions/common_steps.rb:6:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/common_steps.rb:6:in `/^(.*) within a cassette named "([^"]*)"$/'
      features/repos/projects.feature:11:in `When I make request within a cassette named "repos/projects/list"'
    Then the response status should be 200                            # features/step_definitions/common_steps.rb:26
    And the response type should be JSON                              # features/step_definitions/common_steps.rb:45
    And the response should not be empty                              # features/step_definitions/common_steps.rb:60

Failing Scenarios:
cucumber features/repos/projects.feature:6 # Scenario: List
```

See: vcr/vcr#637

Need to update VCR and Webmock to latest versions and do whatever needs to be done to get all the cassettes working.

**Comment by piotrmurach** [comment]
I will shortly merge projects api and will have a quick look at the vcr vs webmock situation.
