### ISSUE TITLE
on_complete': GET https://api.github.com/user/emails: 401 - Bad credentials

### ISSUE THREAD

**Issue by Aravindios** [piotrmurach/github#339]
on_complete': GET https://api.github.com/user/emails: 401 - Bad credentials

/Users/apple/.rvm/gems/ruby-2.3.5/gems/octokit-4.9.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user/emails: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/faraday-0.15.2/lib/faraday/response.rb:9:in `block in call'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/faraday-0.15.2/lib/faraday/response.rb:61:in `on_complete'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/octokit-4.9.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/octokit-4.9.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/faraday-0.15.2/lib/faraday/connection.rb:138:in `get'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/octokit-4.9.0/lib/octokit/connection.rb:156:in `request'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/octokit-4.9.0/lib/octokit/connection.rb:84:in `paginate'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/octokit-4.9.0/lib/octokit/client/users.rb:300:in `emails'
	from /Users/apple/Desktop/ci/app/services/services.rb:117:in `provider_credential'
	from /Users/apple/Desktop/ci/app/services/services.rb:185:in `configuration_repository_service'
	from /Users/apple/Desktop/ci/app/services/onboarding_service.rb:98:in `remote_configuration_repository_valid?'
	from /Users/apple/Desktop/ci/app/services/onboarding_service.rb:61:in `required_keys_and_proper_remote_configuration_repo?'
	from /Users/apple/Desktop/ci/launch.rb:105:in `clone_repo_if_no_local_repo_and_remote_repo_exists'
	from /Users/apple/Desktop/ci/launch.rb:26:in `take_off'
	from /Users/apple/Desktop/ci/config.ru:8:in `block in <main>'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
	from /Users/apple/Desktop/ci/config.ru:in `new'
	from /Users/apple/Desktop/ci/config.ru:in `<main>'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/rack-2.0.5/lib/rack/server.rb:283:in `start'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/rack-2.0.5/lib/rack/server.rb:148:in `start'
	from /Users/apple/.rvm/gems/ruby-2.3.5/gems/rack-2.0.5/bin/rackup:4:in `<top (required)>'
	from /Users/apple/.rvm/gems/ruby-2.3.5/bin/rackup:23:in `load'
	from /Users/apple/.rvm/gems/ruby-2.3.5/bin/rackup:23:in `<main>'
	from /Users/apple/.rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:24:in `eval'
	from /Users/apple/.rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:24:in `<main>'
rake aborted!

**Comment by Aravindios** [comment]
here is the answer -

git config --global --list
open the ~/.gitconfig in file path
check user/emails
if its wrong change it.
then run its successful.
