### ISSUE TITLE
Does Not Work With Ruby 3.0 Unless Using Faraday 1.3

### ISSUE THREAD

**Issue by sshaw** [piotrmurach/github#378]
[1.3 supports Ruby 3](https://github.com/lostisland/faraday/blob/53e4baedc728988ba8f1c48064edc047c54bb799/CHANGELOG.md#v130-2020-12-31). Without it the following error occurs: 

```
/tmp/export-pull-requests >gem install github_api
Successfully installed github_api-0.19.0
1 gem installed
/tmp/export-pull-requests >ruby -vrgithub_api -e'1'
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin18]
/Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday/options.rb:153:in `new': tried to create Proc object without a block (ArgumentError)
	from /Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday/options.rb:153:in `memoized'
	from /Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday/options.rb:234:in `<class:ProxyOptions>'
	from /Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday/options.rb:216:in `<module:Faraday>'
	from /Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday/options.rb:1:in `<top (required)>'
	from <internal:/Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday.rb:80:in `block in require_libs'
	from /Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday.rb:79:in `each'
	from /Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday.rb:79:in `require_libs'
	from /Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday.rb:240:in `<module:Faraday>'
	from /Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/faraday-0.9.2/lib/faraday.rb:16:in `<top (required)>'
	from <internal:/Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/github_api-0.19.0/lib/github_api.rb:5:in `<top (required)>'
	from <internal:/Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
<internal:/Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- github_api (LoadError)
	from <internal:/Users/sshaw/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
```

**Comment by piotrmurach** [comment]
Thanks for reporting this.

The gemspec permits you to install pretty much any version `1.x` of `faraday` dependency:

```ruby
gem.add_dependency "faraday",  ">= 0.8", "< 2"
```
